---
- name: Pull Configuration from Palo Alto Firewalls
  hosts: panos-fw
  gather_facts: False
  connection: local

  vars:
    configs_dir: ./configs/


  tasks:
    - name: Get PanOS Firewall Configuration
      block:
      - name: Get Configration from Firewall
        paloaltonetworks.panos.panos_facts:
          provider: '{{ provider }}'
          gather_subset: 
            - "config"

      - name: print facts
        ansible.builtin.debug:
          var: ansible_facts.net_config
          verbosity: 2

      - name: Debug
        ansible.builtin.set_fact:
          date_time: "{{ lookup ('pipe', 'date +%Y-%m-%d%H:%M:%S') }}"

    - name: GitOps functions
      block:
      - name: Retrieve a repository from a distant location and make it available locally
        ansible.scm.git_retrieve:
          origin:
            url: git@github.com:taruch/ansible-pan-demo.git
        register: repository
     
      - name: Debug repository data
        ansible.builtin.debug:
          var: repository
          verbosity: 2
  
      - name: Add to the repository
        ansible.builtin.copy:
          content: "{{ ansible_facts.net_config }}"
          dest: "{{ repository['path'] }}/{{ inventory_hostname }}.{{ date_time }}"
  
      - name: Publish the changes
        ansible.scm.git_publish:
          commit:
            message: "Backup at {{ date_time }}"
          include: "--all"
          path: "{{ repository['path'] }}"
          user:
            name: "Todd Ruch"
            email: truch@redhat.com
      ### End of GitOps Block
      tags:
        - gitops
        - never
