---
- name: Pull Configuration from Palo Alto Firewalls
  hosts: panos-fw
  gather_facts: False
  connection: local

  tasks:
    - name: Get PanOS Firewall Configuration
      block:
      - name: Get Configration from Firewall
        paloaltonetworks.panos.panos_facts:
          provider: '{{ provider }}'
          gather_subset: 
            - "config"

      - name: print facts
        ansible.builtin.debug:
          var: ansible_facts.net_config
          verbosity: 2

      - name: Debug
        ansible.builtin.set_fact:
          date_time: "{{ lookup ('pipe', 'date +%Y-%m-%d%H:%M:%S') }}"
      ### End of Block
      tags:
        - always

    - name: GitOps functions
      block:
      - name: Retrieve a repository from a distant location and make it available locally
        ansible.scm.git_retrieve:
          origin:
            url: "{{ git_url }}" 
        register: repository
     
      - name: Debug repository data
        ansible.builtin.debug:
          var: repository
          verbosity: 2
  
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: "{{ repository['path'] }}/config_backups"
          state: directory
          mode: '0755'

      - name: Add to the repository
        ansible.builtin.copy:
          content: "{{ ansible_facts.net_config }}"
          dest: "{{ repository['path'] }}/config_backups/{{ inventory_hostname }}"
        register: result

      - name: Publish the changes
        ansible.scm.git_publish:
          commit:
            message: "Backup at {{ date_time }}"
          include: "--all"
          path: "{{ repository['path'] }}"
          user:
            name: "Todd Ruch"
            email: truch@redhat.com
        when: result.changed
      ### End of GitOps Block
      tags:
        - gitops
        - never
