download_url: https://galaxy.ansible.com/download/ansible-scm-1.2.0.tar.gz
format_version: 1.0.0
name: scm
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.2.0
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/scm/versions/1.2.0/
